### ISSUE TITLE
CDSConfig.getInstance() returns null

### ISSUE THREAD

**Issue by JobDoesburg** [icpctools/icpctools#454]

**Comment by deboer-tim** [comment]
Are you using the zip or docker image? Can you post the server.xml or check to see if the jndi feature is enabled? i.e.
```
<server description="ICPC contest data server">
    <featureManager>
       <feature>jndi-1.0</feature>
```

**Comment by JobDoesburg** [comment]
I'm using the docker image, `server.xml`:

```xml
<server description="ICPC contest data server">
    <featureManager>
       <feature>jsp-2.3</feature>
       <feature>servlet-4.0</feature>
       <feature>jndi-1.0</feature>
       <feature>websocket-1.1</feature>
       <feature>appSecurity-3.0</feature>
    </featureManager>

    <!-- If you have root access, change port numbers to httpPort="80" httpsPort="443" -->
    <httpEndpoint host="*" httpPort="8080" httpsPort="8443" id="defaultHttpEndpoint">
       <tcpOptions soReuseAddr="true"/>
       <httpOptions ThrowIOEForInboundConnections="true"/>
    </httpEndpoint>

    <webApplication id="CDS" location="CDS.war" name="CDS" contextRoot="/">
       <application-bnd>
         <security-role name="admin">
         	<user name="admin"/>
         </security-role>
         <security-role name="presAdmin">
            <user name="presAdmin"/>
         </security-role>
         <security-role name="blue">
         	<user name="blue"/>
         </security-role>
         <security-role name="balloon">
         	<user name="balloon"/>
         </security-role>
         <security-role name="trusted">
         	<user name="myicpc"/>
            <user name="live"/>
         </security-role>
         <security-role name="public">
            <user name="presentation"/>
            <user name="public"/>
         </security-role>
         <security-role name="team">
         	<user name="team1"/>
         </security-role>
       </application-bnd>
    </webApplication>

    <httpSession invalidationTimeout="8h"/>

    <keyStore id="defaultKeyStore" password="{xor}FhwPHAswMDMs" />

    <include location="users.xml"/>

    <jndiEntry jndiName="icpc.cds.config" value="${server.config.dir}/config"/>
</server>
```

**Comment by JobDoesburg** [comment]
More extensive error report when loading the web interface of the CDS:

```
Original Exception:

Error Message: java.lang.NullPointerException: Cannot invoke "org.icpc.tools.cds.CDSConfig.getTeamIdFromHost(String)" because "config" is null
Error Code: 500
Target Servlet: ServletNameNotFound
Error Stack: 
java.lang.NullPointerException: Cannot invoke "org.icpc.tools.cds.CDSConfig.getTeamIdFromHost(String)" because "config" is null 
     at org.icpc.tools.cds.service.BasicAuthFilter.doFilter(BasicAuthFilter.java:54) 
     at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) 
     at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56) 
     at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139) 
     at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057) 
     at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314) 
     at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1005) 
     at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279) 
     at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1141) 
     at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:422) 
     at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:381) 
     at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:565) 
     at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:499) 
     at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359) 
     at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326) 
     at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167) 
     at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75) 
     at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504) 
     at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574) 
     at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958) 
     at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047) 
     at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239) 
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) 
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) 
     at java.base/java.lang.Thread.run(Thread.java:831) 
     


Error Page Exception:

Error Message: java.lang.NullPointerException: Cannot read field "contests" because the return value of "org.icpc.tools.cds.CDSConfig.getInstance()" is null
Error Code: 0
Target Servlet: 
Error Stack: 
java.lang.NullPointerException: Cannot read field "contests" because the return value of "org.icpc.tools.cds.CDSConfig.getInstance()" is null 
     at org.icpc.tools.cds.CDSConfig.getContests(CDSConfig.java:538) 
     at com.ibm._jsp._errorPage._jspService(_errorPage.java:267) 
     at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:100) 
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:791) 
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1257) 
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:745) 
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:442) 
     at com.ibm.wsspi.webcontainer.servlet.GenericServletWrapper.handleRequest(GenericServletWrapper.java:118) 
     at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.handleRequest(AbstractJSPExtensionServletWrapper.java:207) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93) 
     at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56) 
     at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010) 
     at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch(WebAppRequestDispatcher.java:1410) 
     at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.forward(WebAppRequestDispatcher.java:171) 
     at org.icpc.tools.cds.service.ErrorService.service(ErrorService.java:31) 
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:791) 
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1257) 
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:745) 
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:442) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93) 
     at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56) 
     at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139) 
     at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010) 
     at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch(WebAppRequestDispatcher.java:1410) 
     at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.forward(WebAppRequestDispatcher.java:171) 
     at com.ibm.ws.webcontainer.webapp.WebApp.sendError(WebApp.java:4350) 
     at com.ibm.ws.webcontainer.webapp.WebApp.handleException(WebApp.java:5146) 
     at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5126) 
     at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314) 
     at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1005) 
     at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279) 
     at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1141) 
     at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:422) 
     at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:381) 
     at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:565) 
     at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:499) 
     at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359) 
     at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326) 
     at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167) 
     at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75) 
     at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504) 
     at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574) 
     at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958) 
     at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047) 
     at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239) 
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) 
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) 
     at java.base/java.lang.Thread.run(Thread.java:831) 

```
